site_name: Portail
theme:
  name: material
  language: fr
  palette:
    - scheme: default
      primary: black
      accent: indigo
    - scheme: slate
      primary: black
      accent: indigo
  features:
    - navigation.tabs          # Onglets horizontaux
    - navigation.sections      # Sections claires dans le menu
    - navigation.top           # Bouton "Retour en haut"
    - navigation.tracking      # Met à jour l'URL selon la lecture
    - content.code.copy        # Bouton copier pour tes scripts Bash
    - search.suggest           # Suggestions dans la barre de recherche
    - search.highlight         # Surlignage des mots trouvés

markdown_extensions:
  - attr_list                  # Indispensable pour le design des cartes
  - md_in_html                 # Indispensable pour ton code HTML/CSS de l'index
  - pymdownx.superfences       # Pour l'affichage propre du code
  - pymdownx.magiclink         # Liens cliquables automatiquement
  - pymdownx.emoji:            # Configuration stable pour les icônes
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

nav:
  - Accueil: index.md
  - Installation Bash: installation.md
  - Projets: projets.md